- judokit-android/src/test/java/com/judokit/android/JudoSharedViewModelTest.kt
> SharedViewModel UnitTests

- .gitignore
- judokit-android/build.gradle
- judokit-android/src/main/AndroidManifest.xml
- Fixed jacoco instrumentation
> - Fixed manifest merge issue

- judokit-android/src/main/java/com/judokit/android/model/PaymentWidgetType.kt
- judokit-android/src/test/java/com/judokit/android/model/PaymentWidgetTypeKtTest.kt
-enable 3DS flow for register card and check card
> EP-1533 3DS incomplete for registercard

- judokit-android-examples/build.gradle
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/espresso/Functions.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/exceptions/ViewNotDefinedException.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/CardEntryRobot.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/ConfigurationRobot.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/ThreeDSecureRobot.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/enum/ViewDefinitions.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/steps/CardEntrySteps.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/steps/ThreeDSecureSteps.kt
- judokit-android/src/main/java/com/judokit/android/model/CardNetwork.kt
- judokit-android/src/main/java/com/judokit/android/ui/cardentry/validation/SecurityCodeValidator.kt
- judokit-android/src/main/res/values/strings.xml
- judokit-android/src/test/java/com/judokit/android/model/CardNetworkTest.kt
- judokit-android/src/test/java/com/judokit/android/ui/cardentry/validation/SecurityCodeValidatorTest.kt
-Added Display amount on button tests
-Added AVS tests
> EP-1549 - Payment / PreAuth Automated Tests (AVS,Display Label on Button)

- build.gradle
- judokit-android-examples/build.gradle
- judokit-android/build.gradle
Context: merchants are not able to use other coroutine version
> update kotlin and coroutines in SDK

- judokit-android/build.gradle
- judokit-android/src/main/java/com/judokit/android/ui/cardverification/ThreeDSOneCardVerificationDialogFragment.kt
-Dismiss the dialog when callback received
-Update SDK version number
> 3DS dismiss dialog when callback received

- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/model/Card.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/model/TestConfiguration.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/model/TestData.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/CardEntryRobot.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/robots/ConfigurationRobot.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/steps/CardEntrySteps.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/steps/PaymentMethodsSteps.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/steps/ThreeDSecureSteps.kt
-Added test models for json parsing
-Read from json file instead of hardcoded data
> Automated testing configuration

- judokit-android-examples/src/main/res/values/arrays.xml
- judokit-android/src/main/java/com/judokit/android/model/Currency.kt
> Add PKR currency

- judokit-android/src/main/java/com/judokit/android/api/model/response/Receipt.kt
- judokit-android/src/main/java/com/judokit/android/model/JudoResult.kt
- judokit-android/src/main/java/com/judokit/android/ui/paymentmethods/PaymentMethodsViewModel.kt
- judokit-android/src/test/java/com/judokit/android/api/model/response/ReceiptTest.kt
@marcghelas can you please test this?
I wasn't able to run the sample app because of `File google-services.json is missing. The Google Services Plugin cannot function without it. `
> Updated the Receipt & JudoResponse models with missing fields

- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
- judokit-android-examples/src/main/res/values/strings.xml
- judokit-android-examples/src/main/res/xml/root_preferences.xml
- judokit-android/src/main/java/com/judokit/android/Judo.kt
- judokit-android/src/main/java/com/judokit/android/JudoExtensions.kt
- judokit-android/src/main/java/com/judokit/android/api/model/request/CheckCardRequest.kt
- judokit-android/src/main/java/com/judokit/android/api/model/request/PaymentRequest.kt
- judokit-android/src/main/java/com/judokit/android/api/model/request/RegisterCardRequest.kt
- judokit-android/src/main/java/com/judokit/android/api/model/request/TokenRequest.kt
- judokit-android/src/main/java/com/judokit/android/ui/cardentry/CardEntryViewModel.kt
- judokit-android/src/main/java/com/judokit/android/ui/paymentmethods/PaymentMethodsViewModel.kt
- judokit-android/src/test/java/com/judokit/android/JudoBuilderTest.kt
- judokit-android/src/test/java/com/judokit/android/JudoExtensionsTest.kt
- judokit-android/src/test/java/com/judokit/android/api/model/request/RegisterCardRequestTest.kt
- judokit-android/src/test/java/com/judokit/android/api/model/request/TokenRequestTest.kt
Added initialRecurringPayment field to Judo configuration object
> EP-1832 - Add initialReccuringPayment flag to payment flows

- judokit-android/src/main/java/com/judokit/android/model/Country.kt
- judokit-android/src/main/java/com/judokit/android/ui/cardentry/components/FormView.kt
- judokit-android/src/main/res/layout/judo_edit_text_input_layout.xml
- judokit-android/src/main/res/layout/payment_call_to_action_view.xml
- judokit-android/src/main/res/values-es/strings.xml
- judokit-android/src/main/res/values-fr/strings.xml
- judokit-android/src/main/res/values/googlepay_strings.xml
- judokit-android/src/main/res/values/strings.xml
- judokit-android/src/test/java/com/judokit/android/model/CountryTest.kt
> Added Spanish and French translations

- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/CardVerificationResult.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardverification/ThreeDSOneCardVerificationDialogFragment.kt
set md parameter from initial payments response when md is not returned by the acs
> Set MD parameter from initial response

- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
- judokit-android-examples/src/main/res/values/strings.xml
- judokit-android-examples/src/main/res/xml/root_preferences.xml
- judokit-android/src/main/AndroidManifest.xml
- judokit-android/src/main/java/com/judopay/judokit/android/Judo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/JudoExtensions.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/exception/NetworkConnectivityException.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/factory/JudoApiServiceFactory.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/interceptor/NetworkConnectivityInterceptor.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/JudoApiCallResult.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/JudoError.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/NetworkTimeout.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardentry/CardEntryFragment.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardverification/ThreeDSOneCardVerificationDialogFragment.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Functions.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/ideal/IdealFragment.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/ideal/IdealViewModel.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/paymentmethods/PaymentMethodsFragment.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/paymentmethods/PaymentMethodsViewModel.kt
- judokit-android/src/main/res/values/strings.xml
- judokit-android/src/test/java/com/judopay/judokit/android/JudoBuilderTest.kt
- judokit-android/src/test/java/com/judopay/judokit/android/api/interceptor/NetworkConnectivityInterceptorTest.kt
- judokit-android/src/test/java/com/judopay/judokit/android/model/NetworkTimeoutTest.kt
- judokit-android/src/test/java/com/judopay/judokit/android/ui/ideal/IdealViewModelTest.kt
- judokit-android/src/test/java/com/judopay/judokit/android/ui/paymentmethods/PaymentMethodsViewModelTest.kt
Added network handling
Added configurable timeouts
> EP-1815 - Handle network errors

- build.gradle
- judokit-android-examples/build.gradle
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Mappers.kt
> Removes PAN_ONLY from GooglePay allowedAuthMethods array

- build.gradle
- judokit-android-examples/build.gradle
- judokit-android/build.gradle
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
- Fixes 'unspecified' listed as a node in pom file transitive dependencies list
> Configuration fixes

- build.gradle
- judokit-android-examples/build.gradle
- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
- judokit-android-examples/src/main/res/values/arrays.xml
- judokit-android/build.gradle
- judokit-android/src/main/AndroidManifest.xml
- judokit-android/src/main/java/com/judopay/judokit/android/Judo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/threedsecure/ThreeDSecureTwo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
- Package version bump
- Update 3DS-SDK dependency version
- `scaExemption` and `challengeRequestIndicator` with no default values
> Release 3.0.8

- judokit-android/src/test/java/com/judopay/judokit/android/ui/cardentry/validation/PostcodeValidatorTest.kt
Sorry, just a minute or so late with the updated unit tests in PostcodeValidatorTest 😬
> CT-2664 Update postcode validation - tests

- judokit-android/src/main/assets/countries.json
The countries.json has been updated with correct value for St. Lucia.
> CT-2722 | Android SDK: Incorrect country code for St. Lucia

- judokit-android-examples/build.gradle
- judokit-android-examples/src/main/java/com/judokit/android/examples/apiclient/ApiClient.kt
- judokit-android-examples/src/main/java/com/judokit/android/examples/settings/fragments/RootFragment.kt
- judokit-android-examples/src/main/res/layout/layout_generate_payment_session.xml
- judokit-android-examples/src/main/res/values/strings.xml
- judokit-android-examples/src/main/res/xml/root_preferences.xml
@RafalOzogJudopay this is a naive implementation, feel free to improve it!
> Adds the ability to generate payment-sessions from the settings screen

- build.gradle
- judokit-android-examples/build.gradle
- judokit-android/build.gradle
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
- 3DS SDK version bump
- Package version bump
> 3DS SDK version bump

- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardentry/CardEntryFragment.kt
- judokit-android/src/main/res/layout/billing_details_form_view.xml
- judokit-android/src/main/res/layout/card_entry_form_view.xml
This commit includes modifications to improve autofill compatibility in the CardEntryFragment. It adds the necessary autofill hints to various input fields for better autofill suggestions and functionality. These changes aim to enhance the user experience by providing accurate autofill suggestions.
> Refactor: Improve autofill compatibility

- judokit-android-examples/src/main/java/com/judokit/android/examples/settings/fragments/RootFragment.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/threedsecure/ThreeDSecureTwo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/Receipt.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/StepUpFlowDetails.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/TransactionDetails.kt
- judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
https://thedojo.atlassian.net/browse/CT-2815
> CT-2815 Step-Up Flow - Android

- .circleci/config.yml
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
* New weekly job to run tests against Android 13, 12 and 11
* Adjust current release testing job to run against Android 14
* New Slack alert for weekly run
* Thanks to Rafal for the permissions fix
> CT-2856 | Backward compatibility testing

- .circleci/config.yml
> Fix device definition

- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/noui/DemoNoUiPaymentActivity.kt
- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayments/TokenPaymentsViewModel.kt
- judokit-android-examples/src/main/res/values/strings.xml
- judokit-android-examples/src/main/res/xml/root_preferences.xml
- judokit-android/api/judokit-android.api
- judokit-android/src/main/java/com/judopay/judokit/android/Judo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthGooglePayRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthTokenRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/TransactionDetails.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Mappers.kt
This reverts commit 378aadbaf66328ca5b2ab45204bea3f6eeb83f3e.
> Revert "CT-2884: Introduction of allowIncrement flag"

- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/noui/DemoNoUiPaymentActivity.kt
- judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayments/TokenPaymentsViewModel.kt
- judokit-android-examples/src/main/res/values/strings.xml
- judokit-android-examples/src/main/res/xml/root_preferences.xml
- judokit-android/api/judokit-android.api
- judokit-android/src/main/java/com/judopay/judokit/android/Judo.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthGooglePayRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthTokenRequest.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/TransactionDetails.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Mappers.kt
This reverts commit ef464e16e80680f37373b3a53dd09ab3099e0abb.
> Reapply "CT-2884: Introduction of allowIncrement flag"

- .circleci/config.yml
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/EspressoExtensions.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Helpers.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/RavelinIntegrationTest.kt
* Use [Orchestrator](https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner#use-android) ensuring each test is independent 
* Add labels to the test suites on Firebase
* [Helper functions](https://stackoverflow.com/a/56499223) to find matchers better with implicit waits
* Do not use `IdlingResource` in certain areas which seems to have helped with flakiness
> Debug & address UI test failures

- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/TestData.kt
* Add tests for step up transactions - more info [here](https://thedojo.atlassian.net/wiki/spaces/FE/pages/3619160090/Testing+step-up+flow)
> CT-2952 | Step up flow UI tests

- judokit-android/src/main/res/layout/billing_details_form_view.xml
- judokit-android/src/main/res/layout/judo_edit_text_input_layout.xml
- judokit-android/src/main/res/values/strings.xml
* Selectors required for billing info tests on React Native SDK
> CT-2903 | Add selectors for RN tests

- fastlane/Fastfile
- gradle/libs.versions.toml
Updates internal dependencies versions
> Migration to user token's username and password pair for sonatype

- judokit-android/api/judokit-android.api
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/EnhancedPaymentDetails.kt
- judokit-android/src/main/java/com/judopay/judokit/android/service/PayloadService.kt
Removes unnecessary properties from "EnhancedPaymentDetails".
> Removes unnecessary params from EnhancedPaymentDetails

- .circleci/config.yml
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Helpers.kt
Include latest Galaxy Tab in Firebase testing, and dismiss keyboard where required.
> CT-3006 | Include tablet in UI testing

- .circleci/config.yml
- build-logic/convention/src/main/kotlin/com/judopay/judokit/AndroidApplicationConfiguration.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/IdealTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/TestData.kt
Include basic tests to test iDEAL functionality, some cleanup here and there
> CT-3005 | iDEAL UI tests

- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
Filling in some remaining gaps from our manual regression tests
> CT-3019 | Add test for primary account details

- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/IdealTest.kt
- judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/RavelinIntegrationTest.kt
Config was not being reset between test suites, causing failures on Firebase testing
> Fix config causing failures on Firebase

- judokit-android/api/judokit-android.api
- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardentry/components/BillingDetailsFormView.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/cardentry/components/DiacriticInsensitiveAdapter.kt
[demo.webm](https://github.com/user-attachments/assets/60ca96aa-c657-4456-8ef2-b7a00fc6f44c)
> Normalizes diacritics in Admin. Divisions selection

- judokit-android-examples/src/main/java/com/judokit/android/examples/settings/fragments/RootFragment.kt
- judokit-android/api/judokit-android.api
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/CardToken.kt
- judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/Receipt.kt
- judokit-android/src/main/java/com/judopay/judokit/android/model/JudoResult.kt
- judokit-android/src/main/java/com/judopay/judokit/android/ui/common/Constants.kt
1. Updates PartnerApi to 6.22.
2. Adds new properties: emailAddress and ownerType.
> Updates PartnerApi to 6.22
